ilas_payment.settings:
  type: config_object
  label: 'ILAS Payment settings'
  mapping:
    test_mode:
      type: boolean
      label: 'Test mode'
    suggested_amounts:
      type: sequence
      label: 'Suggested donation amounts'
      sequence:
        type: integer
    minimum_amount:
      type: integer
      label: 'Minimum donation amount'
    receipt_email_from:
      type: email
      label: 'Receipt email from address'
    stripe_enabled:
      type: boolean
      label: 'Stripe enabled'
    stripe_test_public_key:
      type: string
      label: 'Stripe test publishable key'
    stripe_test_secret_key:
      type: string
      label: 'Stripe test secret key'
    stripe_live_public_key:
      type: string
      label: 'Stripe live publishable key'
    stripe_live_secret_key:
      type: string
      label: 'Stripe live secret key'
    stripe_webhook_secret:
      type: string
      label: 'Stripe webhook secret'
    stripe_processor_id:
      type: integer
      label: 'Stripe processor ID in CiviCRM'
    paypal_enabled:
      type: boolean
      label: 'PayPal enabled'
    paypal_business_email:
      type: email
      label: 'PayPal business email'
    paypal_processor_id:
      type: integer
      label: 'PayPal processor ID in CiviCRM'
    default_financial_type:
      type: string
      label: 'Default financial type'
    send_receipts:
      type: boolean
      label: 'Send automatic receipts'
    receipt_subject:
      type: string
      label: 'Receipt email subject'
    receipt_template:
      type: text
      label: 'Receipt email template'