ilas_civicrm.settings:
  type: config_object
  label: 'ILAS CiviCRM Integration settings'
  mapping:
    enable_webform_integration:
      type: boolean
      label: 'Enable webform integration'
    enable_chatbot_integration:
      type: boolean
      label: 'Enable chatbot integration'
    create_cases_automatically:
      type: boolean
      label: 'Create cases automatically'
    webform_mappings:
      type: text
      label: 'Webform field mappings'
    priority_forms:
      type: sequence
      label: 'Priority forms'
      sequence:
        type: string
    chatbot_api_key:
      type: string
      label: 'Chatbot API key'
    chatbot_create_anonymous:
      type: boolean
      label: 'Create anonymous contacts'
    urgent_intents:
      type: text
      label: 'Urgent intents'
    custom_activity_types:
      type: text
      label: 'Custom activity types'
    service_area_tags:
      type: text
      label: 'Service area tags'
    auto_tag_rules:
      type: text
      label: 'Auto-tagging rules'