ilas_chatbot.settings:
  type: config_object
  label: 'ILAS Chatbot settings'
  mapping:
    agent_id:
      type: string
      label: 'Dialogflow Agent ID'
    language_code:
      type: string
      label: 'Language Code'
    welcome_intent:
      type: string
      label: 'Welcome Intent'
    form_mappings:
      type: sequence
      label: 'Form type to URL mappings'
      sequence:
        type: string
        label: 'Form URL'
    trusted_domains:
      type: sequence
      label: 'Trusted domains for forms'
      sequence:
        type: string
        label: 'Domain'
    webhook_secret:
      type: string
      label: 'Webhook secret token'
    webhook_allowed_ips:
      type: sequence
      label: 'Allowed IP addresses for webhook'
      sequence:
        type: string
        label: 'IP Address'
    form_titles:
      type: sequence
      label: 'Form type to title mappings'
      sequence:
        type: string
        label: 'Form title'
    form_descriptions:
      type: sequence
      label: 'Form type to description mappings'
      sequence:
        type: string
        label: 'Form description'
    legal_categories:
      type: sequence
      label: 'Legal categories for quick replies'
      sequence:
        type: string
        label: 'Category'
    css_override:
      type: text
      label: 'Custom CSS override'
    load_globally:
      type: boolean
      label: 'Load chatbot globally'
    enable_analytics:
      type: boolean
      label: 'Enable analytics tracking'